CREATE TABLE `prospective_forecast_snapshots` (
	`id` int AUTO_INCREMENT NOT NULL,
	`source_key` varchar(120) NOT NULL,
	`issue_key` varchar(32) NOT NULL,
	`issue_time` timestamp NOT NULL,
	`target_date` varchar(10) NOT NULL,
	`horizon_days` int NOT NULL,
	`rainfall_lag_1d_mm` decimal(9,2) NOT NULL,
	`rainfall_lag_3d_mm` decimal(9,2) NOT NULL,
	`rainfall_lag_7d_mm` decimal(9,2) NOT NULL,
	`rainfall_lag_14d_mm` decimal(9,2) NOT NULL,
	`rainfall_lag_30d_mm` decimal(9,2) NOT NULL,
	`discharge_lag_1d_m3s` decimal(12,2) NOT NULL,
	`discharge_lag_3d_m3s` decimal(12,2) NOT NULL,
	`discharge_lag_7d_m3s` decimal(12,2) NOT NULL,
	`discharge_lag_14d_m3s` decimal(12,2) NOT NULL,
	`discharge_lag_30d_m3s` decimal(12,2) NOT NULL,
	`discharge_p25_m3s` decimal(12,2),
	`discharge_p75_m3s` decimal(12,2),
	`deep_soil_moisture` decimal(9,5),
	`projection_status` varchar(64) NOT NULL,
	`model_version` varchar(120) NOT NULL,
	`input_coverage` json NOT NULL,
	`quality_flags` json NOT NULL,
	`created_at` timestamp NOT NULL DEFAULT (now()),
	`updated_at` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `prospective_forecast_snapshots_id` PRIMARY KEY(`id`),
	CONSTRAINT `prospective_forecast_issue_target` UNIQUE(`source_key`,`issue_key`,`target_date`)
);
